// src/templates/ionicReact/component/{component}.tsx
import React from 'react';
import {

} from '@ionic/react';
import {

} from 'ionicons/icons';
import './{Name}.scss';

type Props = {

}

const {Name}: React.FC<Props> = () => {
  return (
    <div className="{kebabCase}">
      <h2>{Name} Component</h2>
    </div>
  );
};

{Name}.defaultProps = {

}

export default {Name};

// src/templates/ionicVue/component/{component}.vue
<template>
  <div className="{kebabCase}">
    <h2>My Component</h2>
  </div>
</template>

<script lang="ts">
import {

} from '@ionic/vue';
import {

} from 'ionicons/icons';
import './{Name}.scss';

export default {
  name: '{Name}',
  props: {

  },
  components: {

  },
  setup() {
    return {

    }
  }
}
</script>
